export const TECH_KEYWORDS = {
  backend: {
    'django': 'Django',
    'flask': 'Flask',
    'fastapi': 'FastAPI',
    'express': 'Express.js',
    'expressjs': 'Express.js',
    'nestjs': 'NestJS',
    'nest.js': 'NestJS',
    'spring boot': 'Spring Boot',
    'spring-boot': 'Spring Boot',
    'springboot': 'Spring Boot',
    'laravel': 'Laravel',
    'ruby on rails': 'Ruby on Rails',
    'rails': 'Ruby on Rails',
    'asp.net': 'ASP.NET',
    'dotnet': '.NET',
    '.net core': '.NET Core',
    'gin': 'Gin',
    'echo': 'Echo',
    'fiber': 'Fiber',
    'actix': 'Actix',
    'rocket': 'Rocket',
    'axum': 'Axum',
    'ktor': 'Ktor',
    'micronaut': 'Micronaut',
    'quarkus': 'Quarkus',
    'adonisjs': 'AdonisJS',
    'koa': 'Koa',
    'hapi': 'Hapi',
    'sails': 'Sails.js',
    'symfony': 'Symfony',
    'strapi': 'Strapi',
  },

  frontend: {
    'react': 'React',
    'reactjs': 'React',
    'vue': 'Vue.js',
    'vuejs': 'Vue.js',
    'angular': 'Angular',
    'svelte': 'Svelte',
    'sveltekit': 'SvelteKit',
    'next.js': 'Next.js',
    'nextjs': 'Next.js',
    'nuxt': 'Nuxt.js',
    'gatsby': 'Gatsby',
    'remix': 'Remix',
    'solid.js': 'Solid.js',
    'solidjs': 'Solid.js',
    'qwik': 'Qwik',
    'astro': 'Astro',
    'preact': 'Preact',
    'lit': 'Lit',
    'alpine.js': 'Alpine.js',
    'htmx': 'HTMX',
    'ember': 'Ember.js',
    'backbone': 'Backbone.js',
  },

  mobile: {
    'react native': 'React Native',
    'react-native': 'React Native',
    'flutter': 'Flutter',
    'ionic': 'Ionic',
    'capacitor': 'Capacitor',
    'cordova': 'Cordova',
    'xamarin': 'Xamarin',
    'nativescript': 'NativeScript',
    'expo': 'Expo',
  },

  orm: {
    'prisma': 'Prisma',
    'typeorm': 'TypeORM',
    'sequelize': 'Sequelize',
    'mongoose': 'Mongoose',
    'sqlalchemy': 'SQLAlchemy',
    'hibernate': 'Hibernate',
    'knex': 'Knex.js',
    'drizzle': 'Drizzle ORM',
    'kysely': 'Kysely',
    'objection': 'Objection.js',
  },

  infrastructure: {
    'docker': 'Docker',
    'kubernetes': 'Kubernetes',
    'k8s': 'Kubernetes',
    'aws': 'AWS',
    'amazon web services': 'AWS',
    'gcp': 'Google Cloud',
    'google cloud': 'Google Cloud',
    'azure': 'Azure',
    'heroku': 'Heroku',
    'vercel': 'Vercel',
    'netlify': 'Netlify',
    'digitalocean': 'DigitalOcean',
    'linode': 'Linode',
    'cloudflare': 'Cloudflare',
    'terraform': 'Terraform',
    'ansible': 'Ansible',
    'puppet': 'Puppet',
    'chef': 'Chef',
    'vagrant': 'Vagrant',
    'railway': 'Railway',
    'render': 'Render',
    'fly.io': 'Fly.io',
  },

  api: {
    'rest api': 'REST',
    'restful': 'REST',
    'rest': 'REST',
    'graphql': 'GraphQL',
    'apollo': 'Apollo GraphQL',
    'grpc': 'gRPC',
    'websocket': 'WebSocket',
    'socket.io': 'Socket.io',
    'trpc': 'tRPC',
    'openapi': 'OpenAPI',
    'swagger': 'Swagger',
    'postman': 'Postman',
  },

  messaging: {
    'rabbitmq': 'RabbitMQ',
    'kafka': 'Apache Kafka',
    'celery': 'Celery',
    'redis queue': 'Redis Queue',
    'bull': 'Bull',
    'bullmq': 'BullMQ',
    'sqs': 'AWS SQS',
    'pubsub': 'Pub/Sub',
    'nats': 'NATS',
    'activemq': 'ActiveMQ',
  },

  buildTools: {
    'webpack': 'Webpack',
    'vite': 'Vite',
    'rollup': 'Rollup',
    'parcel': 'Parcel',
    'esbuild': 'esbuild',
    'turbopack': 'Turbopack',
    'gulp': 'Gulp',
    'grunt': 'Grunt',
    'babel': 'Babel',
    'swc': 'SWC',
    'tsup': 'tsup',
  },

  styling: {
    'tailwind': 'Tailwind CSS',
    'tailwindcss': 'Tailwind CSS',
    'bootstrap': 'Bootstrap',
    'material ui': 'Material-UI',
    'mui': 'Material-UI',
    'chakra ui': 'Chakra UI',
    'ant design': 'Ant Design',
    'bulma': 'Bulma',
    'foundation': 'Foundation',
    'sass': 'Sass',
    'scss': 'SCSS',
    'less': 'Less',
    'styled-components': 'styled-components',
    'emotion': 'Emotion',
    'css modules': 'CSS Modules',
    'postcss': 'PostCSS',
    'shadcn': 'shadcn/ui',
  },

  stateManagement: {
    'redux': 'Redux',
    'mobx': 'MobX',
    'zustand': 'Zustand',
    'recoil': 'Recoil',
    'jotai': 'Jotai',
    'xstate': 'XState',
    'valtio': 'Valtio',
    'pinia': 'Pinia',
    'vuex': 'Vuex',
    'ngrx': 'NgRx',
  },

  auth: {
    'auth0': 'Auth0',
    'clerk': 'Clerk',
    'firebase auth': 'Firebase Auth',
    'passport': 'Passport.js',
    'next-auth': 'NextAuth.js',
    'nextauth': 'NextAuth.js',
    'jwt': 'JWT',
    'oauth': 'OAuth',
    'keycloak': 'Keycloak',
    'okta': 'Okta',
    'cognito': 'AWS Cognito',
  },

  monitoring: {
    'sentry': 'Sentry',
    'datadog': 'Datadog',
    'new relic': 'New Relic',
    'prometheus': 'Prometheus',
    'grafana': 'Grafana',
    'elk': 'ELK Stack',
    'elasticsearch': 'Elasticsearch',
    'logstash': 'Logstash',
    'kibana': 'Kibana',
    'splunk': 'Splunk',
    'mixpanel': 'Mixpanel',
    'amplitude': 'Amplitude',
    'google analytics': 'Google Analytics',
  },

  cms: {
    'wordpress': 'WordPress',
    'contentful': 'Contentful',
    'sanity': 'Sanity',
    'strapi': 'Strapi',
    'ghost': 'Ghost',
    'payload': 'Payload CMS',
    'directus': 'Directus',
    'prismic': 'Prismic',
    'storyblok': 'Storyblok',
  },

  languages: {
    'python': 'Python',
    'javascript': 'JavaScript',
    'typescript': 'TypeScript',
    'java': 'Java',
    'go': 'Go',
    'golang': 'Go',
    'rust': 'Rust',
    'c++': 'C++',
    'cpp': 'C++',
    'c#': 'C#',
    'csharp': 'C#',
    'ruby': 'Ruby',
    'php': 'PHP',
    'swift': 'Swift',
    'kotlin': 'Kotlin',
    'scala': 'Scala',
    'elixir': 'Elixir',
    'dart': 'Dart',
    'r': 'R',
  },

  packageManagers: {
    'npm': 'npm',
    'yarn': 'Yarn',
    'pnpm': 'pnpm',
    'pip': 'pip',
    'poetry': 'Poetry',
    'pipenv': 'Pipenv',
    'maven': 'Maven',
    'gradle': 'Gradle',
    'cargo': 'Cargo',
    'composer': 'Composer',
    'bundle': 'Bundler',
  },

  versionControl: {
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'bitbucket': 'Bitbucket',
    'svn': 'SVN',
  },
} as const;

export const ARCH_KEYWORDS = {
  'microservices': 'Microservices',
  'monolith': 'Monolith',
  'event-driven': 'Event-Driven',
  'cqrs': 'CQRS',
  'layered': 'Layered Architecture',
  'serverless': 'Serverless',
  'hexagonal architecture': 'Hexagonal Architecture',
  'clean architecture': 'Clean Architecture',
  'domain-driven design': 'Domain-Driven Design',
  'ddd': 'Domain-Driven Design',
  'modular': 'Modular Architecture',
  'client-server': 'Client-Server',
  'service-oriented': 'Service-Oriented Architecture',
  'soa': 'Service-Oriented Architecture',
  'distributed system': 'Distributed System',
  'n-tier': 'N-Tier Architecture',
} as const;

export const DB_KEYWORDS = {
    'postgresql': 'PostgreSQL',
    'postgres': 'PostgreSQL',
    'mysql': 'MySQL',
    'mongodb': 'MongoDB',
    'mongo': 'MongoDB',
    'redis': 'Redis',
    'sqlite': 'SQLite',
    'elasticsearch': 'Elasticsearch',
    'cassandra': 'Cassandra',
    'dynamodb': 'DynamoDB',
    'mariadb': 'MariaDB',
    'oracle': 'Oracle',
    'mssql': 'MS SQL Server',
    'sql server': 'MS SQL Server',
    'cockroachdb': 'CockroachDB',
    'timescaledb': 'TimescaleDB',
    'influxdb': 'InfluxDB',
    'neo4j': 'Neo4j',
    'arangodb': 'ArangoDB',
    'couchdb': 'CouchDB',
    'firestore': 'Firestore',
    'supabase': 'Supabase',
    'planetscale': 'PlanetScale',
    'fauna': 'Fauna',
    'clickhouse': 'ClickHouse',
} as const;

export const CI_CD_KEYWORDS = {
    'github actions': 'GitHub Actions',
    'gitlab ci': 'GitLab CI',
    'circle ci': 'CircleCI',
    'circleci': 'CircleCI',
    'jenkins': 'Jenkins',
    'travis ci': 'Travis CI',
    'travis': 'Travis CI',
    'azure devops': 'Azure DevOps',
    'bitbucket pipelines': 'Bitbucket Pipelines',
    'drone': 'Drone',
    'teamcity': 'TeamCity',
    'bamboo': 'Bamboo',
    'argo cd': 'Argo CD',
} as const;

export const TESTING_KEYWORDS = {
    'jest': 'Jest',
    'vitest': 'Vitest',
    'mocha': 'Mocha',
    'chai': 'Chai',
    'pytest': 'pytest',
    'unittest': 'unittest',
    'junit': 'JUnit',
    'testng': 'TestNG',
    'cypress': 'Cypress',
    'playwright': 'Playwright',
    'selenium': 'Selenium',
    'puppeteer': 'Puppeteer',
    'testing library': 'Testing Library',
    'react testing library': 'React Testing Library',
    'jasmine': 'Jasmine',
    'karma': 'Karma',
    'ava': 'AVA',
    'tape': 'Tape',
} as const;