export const TECH_KEYWORDS = {
  backend: {
    'django': 'Django',
    'flask': 'Flask',
    'fastapi': 'FastAPI',
    'express': 'Express.js',
    'expressjs': 'Express.js',
    'nestjs': 'NestJS',
    'nest.js': 'NestJS',
    'spring boot': 'Spring Boot',
    'spring-boot': 'Spring Boot',
    'springboot': 'Spring Boot',
    'spring': 'Spring',
    'laravel': 'Laravel',
    'ruby on rails': 'Ruby on Rails',
    'rails': 'Ruby on Rails',
    'asp.net': 'ASP.NET',
    'dotnet': '.NET',
    '.net core': '.NET Core',
    'gin': 'Gin',
    'echo': 'Echo',
    'fiber': 'Fiber',
    'actix': 'Actix',
    'rocket': 'Rocket',
    'axum': 'Axum',
    'ktor': 'Ktor',
    'micronaut': 'Micronaut',
    'quarkus': 'Quarkus',
    'adonisjs': 'AdonisJS',
    'koa': 'Koa',
    'hapi': 'Hapi',
    'sails': 'Sails.js',
    'symfony': 'Symfony',
    'strapi': 'Strapi',
    'nginx': 'Nginx',
    'apache': 'Apache',
  },

  frontend: {
    'react': 'React',
    'reactjs': 'React',
    'vue': 'Vue.js',
    'vuejs': 'Vue.js',
    'angular': 'Angular',
    'svelte': 'Svelte',
    'sveltekit': 'SvelteKit',
    'next.js': 'Next.js',
    'nextjs': 'Next.js',
    'nuxt': 'Nuxt.js',
    'gatsby': 'Gatsby',
    'remix': 'Remix',
    'solid.js': 'Solid.js',
    'solidjs': 'Solid.js',
    'qwik': 'Qwik',
    'astro': 'Astro',
    'preact': 'Preact',
    'lit': 'Lit',
    'alpine.js': 'Alpine.js',
    'htmx': 'HTMX',
    'ember': 'Ember.js',
    'backbone': 'Backbone.js',
    'webgl': 'WebGL',
    'three.js': 'Three.js',
    'threejs': 'Three.js',
    'd3': 'D3.js',
    'd3.js': 'D3.js',
  },

  mobile: {
    'react native': 'React Native',
    'react-native': 'React Native',
    'flutter': 'Flutter',
    'ionic': 'Ionic',
    'capacitor': 'Capacitor',
    'cordova': 'Cordova',
    'xamarin': 'Xamarin',
    'nativescript': 'NativeScript',
    'expo': 'Expo',
    'swiftui': 'SwiftUI',
    'uikit': 'UIKit',
    'jetpack compose': 'Jetpack Compose',
    'android sdk': 'Android SDK',
    'kotlin multiplatform': 'Kotlin Multiplatform',
    'kmp': 'Kotlin Multiplatform',
  },

  ml_ai: {
    'tensorflow': 'TensorFlow',
    'pytorch': 'PyTorch',
    'torch': 'PyTorch',
    'scikit-learn': 'scikit-learn',
    'sklearn': 'scikit-learn',
    'keras': 'Keras',
    'hugging face': 'Hugging Face',
    'huggingface': 'Hugging Face',
    'transformers': 'Hugging Face Transformers',
    'langchain': 'LangChain',
    'langgraph': 'LangGraph',
    'openai': 'OpenAI API',
    'llama': 'LLaMA',
    'ollama': 'Ollama',
    'xgboost': 'XGBoost',
    'lightgbm': 'LightGBM',
    'catboost': 'CatBoost',
    'opencv': 'OpenCV',
    'spacy': 'spaCy',
    'nltk': 'NLTK',
    'mlflow': 'MLflow',
    'wandb': 'Weights & Biases',
    'weights and biases': 'Weights & Biases',
    'ray': 'Ray',
    'cuda': 'CUDA',
    'onnx': 'ONNX',
    'stable diffusion': 'Stable Diffusion',
    'vector database': 'Vector Database',
    'pinecone': 'Pinecone',
    'weaviate': 'Weaviate',
    'chromadb': 'ChromaDB',
    'faiss': 'FAISS',
    'rag': 'RAG',
  },

  data: {
    'pandas': 'Pandas',
    'numpy': 'NumPy',
    'spark': 'Apache Spark',
    'apache spark': 'Apache Spark',
    'pyspark': 'PySpark',
    'hadoop': 'Hadoop',
    'dbt': 'dbt',
    'airflow': 'Apache Airflow',
    'apache airflow': 'Apache Airflow',
    'prefect': 'Prefect',
    'dagster': 'Dagster',
    'kafka': 'Apache Kafka',
    'flink': 'Apache Flink',
    'snowflake': 'Snowflake',
    'bigquery': 'BigQuery',
    'redshift': 'Redshift',
    'databricks': 'Databricks',
    'tableau': 'Tableau',
    'power bi': 'Power BI',
    'looker': 'Looker',
    'metabase': 'Metabase',
    'great expectations': 'Great Expectations',
    'dask': 'Dask',
    'polars': 'Polars',
  },

  orm: {
    'prisma': 'Prisma',
    'typeorm': 'TypeORM',
    'sequelize': 'Sequelize',
    'mongoose': 'Mongoose',
    'sqlalchemy': 'SQLAlchemy',
    'hibernate': 'Hibernate',
    'knex': 'Knex.js',
    'drizzle': 'Drizzle ORM',
    'kysely': 'Kysely',
    'objection': 'Objection.js',
    'entity framework': 'Entity Framework',
    'ef core': 'EF Core',
    'active record': 'Active Record',
  },

  infrastructure: {
    'docker': 'Docker',
    'kubernetes': 'Kubernetes',
    'k8s': 'Kubernetes',
    'helm': 'Helm',
    'istio': 'Istio',
    'aws': 'AWS',
    'amazon web services': 'AWS',
    'gcp': 'Google Cloud',
    'google cloud': 'Google Cloud',
    'azure': 'Azure',
    'heroku': 'Heroku',
    'vercel': 'Vercel',
    'netlify': 'Netlify',
    'digitalocean': 'DigitalOcean',
    'linode': 'Linode',
    'cloudflare': 'Cloudflare',
    'terraform': 'Terraform',
    'ansible': 'Ansible',
    'puppet': 'Puppet',
    'chef': 'Chef',
    'vagrant': 'Vagrant',
    'railway': 'Railway',
    'render': 'Render',
    'fly.io': 'Fly.io',
    'pulumi': 'Pulumi',
    'vault': 'HashiCorp Vault',
    'consul': 'Consul',
    'lambda': 'AWS Lambda',
    'ec2': 'AWS EC2',
    's3': 'AWS S3',
    'ecs': 'AWS ECS',
    'eks': 'AWS EKS',
  },

  api: {
    'rest api': 'REST',
    'restful': 'REST',
    'rest': 'REST',
    'graphql': 'GraphQL',
    'apollo': 'Apollo GraphQL',
    'grpc': 'gRPC',
    'websocket': 'WebSocket',
    'socket.io': 'Socket.io',
    'trpc': 'tRPC',
    'openapi': 'OpenAPI',
    'swagger': 'Swagger',
    'postman': 'Postman',
    'webhook': 'Webhooks',
    'protobuf': 'Protocol Buffers',
  },

  messaging: {
    'rabbitmq': 'RabbitMQ',
    'kafka': 'Apache Kafka',
    'celery': 'Celery',
    'redis queue': 'Redis Queue',
    'bull': 'Bull',
    'bullmq': 'BullMQ',
    'sqs': 'AWS SQS',
    'pubsub': 'Pub/Sub',
    'nats': 'NATS',
    'activemq': 'ActiveMQ',
    'sns': 'AWS SNS',
    'eventbridge': 'AWS EventBridge',
  },

  buildTools: {
    'webpack': 'Webpack',
    'vite': 'Vite',
    'rollup': 'Rollup',
    'parcel': 'Parcel',
    'esbuild': 'esbuild',
    'turbopack': 'Turbopack',
    'turbo': 'Turborepo',
    'turborepo': 'Turborepo',
    'nx': 'Nx',
    'gulp': 'Gulp',
    'grunt': 'Grunt',
    'babel': 'Babel',
    'swc': 'SWC',
    'tsup': 'tsup',
    'make': 'Makefile',
    'cmake': 'CMake',
  },

  styling: {
    'tailwind': 'Tailwind CSS',
    'tailwindcss': 'Tailwind CSS',
    'bootstrap': 'Bootstrap',
    'material ui': 'Material-UI',
    'mui': 'Material-UI',
    'chakra ui': 'Chakra UI',
    'ant design': 'Ant Design',
    'bulma': 'Bulma',
    'sass': 'Sass',
    'scss': 'SCSS',
    'less': 'Less',
    'styled-components': 'styled-components',
    'emotion': 'Emotion',
    'css modules': 'CSS Modules',
    'postcss': 'PostCSS',
    'shadcn': 'shadcn/ui',
    'radix ui': 'Radix UI',
    'headless ui': 'Headless UI',
    'framer motion': 'Framer Motion',
  },

  stateManagement: {
    'redux': 'Redux',
    'mobx': 'MobX',
    'zustand': 'Zustand',
    'recoil': 'Recoil',
    'jotai': 'Jotai',
    'xstate': 'XState',
    'valtio': 'Valtio',
    'pinia': 'Pinia',
    'vuex': 'Vuex',
    'ngrx': 'NgRx',
    'react query': 'React Query',
    'tanstack query': 'TanStack Query',
    'swr': 'SWR',
    'apollo client': 'Apollo Client',
  },

  auth: {
    'auth0': 'Auth0',
    'clerk': 'Clerk',
    'firebase auth': 'Firebase Auth',
    'passport': 'Passport.js',
    'next-auth': 'NextAuth.js',
    'nextauth': 'NextAuth.js',
    'jwt': 'JWT',
    'oauth': 'OAuth',
    'oauth2': 'OAuth 2.0',
    'keycloak': 'Keycloak',
    'okta': 'Okta',
    'cognito': 'AWS Cognito',
    'saml': 'SAML',
    'openid connect': 'OpenID Connect',
    'oidc': 'OpenID Connect',
  },

  monitoring: {
    'sentry': 'Sentry',
    'datadog': 'Datadog',
    'new relic': 'New Relic',
    'prometheus': 'Prometheus',
    'grafana': 'Grafana',
    'elk': 'ELK Stack',
    'elasticsearch': 'Elasticsearch',
    'logstash': 'Logstash',
    'kibana': 'Kibana',
    'splunk': 'Splunk',
    'mixpanel': 'Mixpanel',
    'amplitude': 'Amplitude',
    'google analytics': 'Google Analytics',
    'opentelemetry': 'OpenTelemetry',
    'jaeger': 'Jaeger',
    'zipkin': 'Zipkin',
    'pagerduty': 'PagerDuty',
    'cloudwatch': 'AWS CloudWatch',
  },

  cms: {
    'wordpress': 'WordPress',
    'contentful': 'Contentful',
    'sanity': 'Sanity',
    'strapi': 'Strapi',
    'ghost': 'Ghost',
    'payload': 'Payload CMS',
    'directus': 'Directus',
    'prismic': 'Prismic',
    'storyblok': 'Storyblok',
  },

  packageManagers: {
    'npm': 'npm',
    'yarn': 'Yarn',
    'pnpm': 'pnpm',
    'pip': 'pip',
    'poetry': 'Poetry',
    'pipenv': 'Pipenv',
    'maven': 'Maven',
    'gradle': 'Gradle',
    'cargo': 'Cargo',
    'composer': 'Composer',
    'bundle': 'Bundler',
    'bun': 'Bun',
  },

  versionControl: {
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'bitbucket': 'Bitbucket',
    'svn': 'SVN',
  },
} as const;

export const ARCH_KEYWORDS = {
  'microservices': 'Microservices',
  'monolith': 'Monolith',
  'event-driven': 'Event-Driven',
  'event driven': 'Event-Driven',
  'cqrs': 'CQRS',
  'layered': 'Layered Architecture',
  'serverless': 'Serverless',
  'hexagonal architecture': 'Hexagonal Architecture',
  'clean architecture': 'Clean Architecture',
  'domain-driven design': 'Domain-Driven Design',
  'ddd': 'Domain-Driven Design',
  'modular': 'Modular Architecture',
  'client-server': 'Client-Server',
  'service-oriented': 'Service-Oriented Architecture',
  'soa': 'Service-Oriented Architecture',
  'distributed system': 'Distributed System',
  'distributed systems': 'Distributed System',
  'n-tier': 'N-Tier Architecture',
  'multi-tenant': 'Multi-Tenant',
  'multi-tenancy': 'Multi-Tenant',
  'cloud-native': 'Cloud-Native',
  'api gateway': 'API Gateway',
  'service mesh': 'Service Mesh',
  'event sourcing': 'Event Sourcing',
  'pub/sub': 'Pub/Sub',
  'monorepo': 'Monorepo',
} as const;

export const DB_KEYWORDS = {
  'postgresql': 'PostgreSQL',
  'postgres': 'PostgreSQL',
  'mysql': 'MySQL',
  'mongodb': 'MongoDB',
  'mongo': 'MongoDB',
  'redis': 'Redis',
  'sqlite': 'SQLite',
  'elasticsearch': 'Elasticsearch',
  'cassandra': 'Cassandra',
  'dynamodb': 'DynamoDB',
  'mariadb': 'MariaDB',
  'oracle': 'Oracle',
  'mssql': 'MS SQL Server',
  'sql server': 'MS SQL Server',
  'cockroachdb': 'CockroachDB',
  'timescaledb': 'TimescaleDB',
  'influxdb': 'InfluxDB',
  'neo4j': 'Neo4j',
  'arangodb': 'ArangoDB',
  'couchdb': 'CouchDB',
  'firestore': 'Firestore',
  'firebase': 'Firebase',
  'supabase': 'Supabase',
  'planetscale': 'PlanetScale',
  'fauna': 'Fauna',
  'clickhouse': 'ClickHouse',
  'pinecone': 'Pinecone',
  'weaviate': 'Weaviate',
  'chromadb': 'ChromaDB',
  'qdrant': 'Qdrant',
  'snowflake': 'Snowflake',
  'bigquery': 'BigQuery',
  'redshift': 'Redshift',
} as const;

export const CI_CD_KEYWORDS = {
  'github actions': 'GitHub Actions',
  'gitlab ci': 'GitLab CI',
  'gitlab ci/cd': 'GitLab CI',
  'circle ci': 'CircleCI',
  'circleci': 'CircleCI',
  'jenkins': 'Jenkins',
  'travis ci': 'Travis CI',
  'travis': 'Travis CI',
  'azure devops': 'Azure DevOps',
  'azure pipelines': 'Azure Pipelines',
  'bitbucket pipelines': 'Bitbucket Pipelines',
  'drone': 'Drone',
  'teamcity': 'TeamCity',
  'bamboo': 'Bamboo',
  'argo cd': 'Argo CD',
  'argocd': 'Argo CD',
  'flux': 'Flux',
  'tekton': 'Tekton',
  'spinnaker': 'Spinnaker',
  'fastlane': 'Fastlane',
} as const;

export const TESTING_KEYWORDS = {
  'jest': 'Jest',
  'vitest': 'Vitest',
  'mocha': 'Mocha',
  'chai': 'Chai',
  'pytest': 'pytest',
  'unittest': 'unittest',
  'junit': 'JUnit',
  'testng': 'TestNG',
  'cypress': 'Cypress',
  'playwright': 'Playwright',
  'selenium': 'Selenium',
  'puppeteer': 'Puppeteer',
  'testing library': 'Testing Library',
  'react testing library': 'React Testing Library',
  'jasmine': 'Jasmine',
  'karma': 'Karma',
  'ava': 'AVA',
  'tape': 'Tape',
  'supertest': 'Supertest',
  'k6': 'k6',
  'locust': 'Locust',
  'storybook': 'Storybook',
  'detox': 'Detox',
  'appium': 'Appium',
  'mockito': 'Mockito',
} as const;

export const SENIORITY_KEYWORDS = {
  'principal engineer': 'Principal',
  'principal software engineer': 'Principal',
  'principal developer': 'Principal',
  'staff engineer': 'Staff',
  'staff software engineer': 'Staff',
  'staff developer': 'Staff',
  'lead engineer': 'Lead',
  'lead developer': 'Lead',
  'tech lead': 'Lead',
  'technical lead': 'Lead',
  'team lead': 'Lead',
  'senior engineer': 'Senior',
  'senior software engineer': 'Senior',
  'senior developer': 'Senior',
  'sr engineer': 'Senior',
  'sr. engineer': 'Senior',
  'sr developer': 'Senior',
  'sr. developer': 'Senior',
  'senior': 'Senior',
  'sr': 'Senior',
  'mid-level': 'Mid',
  'mid level': 'Mid',
  'intermediate engineer': 'Mid',
  'junior engineer': 'Junior',
  'junior developer': 'Junior',
  'jr engineer': 'Junior',
  'jr. engineer': 'Junior',
  'jr developer': 'Junior',
  'jr. developer': 'Junior',
  'junior': 'Junior',
  'jr': 'Junior',
  'intern': 'Intern',
  'internship': 'Intern',
} as const;

export const ROLE_KEYWORDS = {
  'software engineer': 'Software Engineer',
  'software developer': 'Software Engineer',
  'full stack developer': 'Full Stack Engineer',
  'full stack engineer': 'Full Stack Engineer',
  'fullstack engineer': 'Full Stack Engineer',
  'fullstack developer': 'Full Stack Engineer',
  'backend developer': 'Backend Engineer',
  'backend engineer': 'Backend Engineer',
  'frontend developer': 'Frontend Engineer',
  'frontend engineer': 'Frontend Engineer',
  'machine learning engineer': 'Machine Learning Engineer',
  'ml engineer': 'Machine Learning Engineer',
  'ai engineer': 'AI Engineer',
  'ai/ml engineer': 'AI/ML Engineer',
  'llm engineer': 'LLM Engineer',
  'data engineer': 'Data Engineer',
  'data scientist': 'Data Scientist',
  'data analyst': 'Data Analyst',
  'analytics engineer': 'Analytics Engineer',
  'devops engineer': 'DevOps Engineer',
  'site reliability engineer': 'Site Reliability Engineer',
  'sre': 'Site Reliability Engineer',
  'platform engineer': 'Platform Engineer',
  'infrastructure engineer': 'Infrastructure Engineer',
  'cloud engineer': 'Cloud Engineer',
  'mobile developer': 'Mobile Engineer',
  'mobile engineer': 'Mobile Engineer',
  'ios developer': 'iOS Engineer',
  'ios engineer': 'iOS Engineer',
  'android developer': 'Android Engineer',
  'android engineer': 'Android Engineer',
  'security engineer': 'Security Engineer',
  'application security engineer': 'AppSec Engineer',
  'blockchain developer': 'Blockchain Engineer',
  'smart contract developer': 'Smart Contract Developer',
  'game developer': 'Game Developer',
  'embedded software engineer': 'Embedded Engineer',
  'firmware engineer': 'Firmware Engineer',
  'solutions architect': 'Solutions Architect',
  'software architect': 'Software Architect',
} as const;

export const LANGUAGE_KEYWORDS = {
  'python': 'Python',
  'javascript': 'JavaScript',
  'typescript': 'TypeScript',
  'java': 'Java',
  'go': 'Go',
  'golang': 'Go',
  'rust': 'Rust',
  'c++': 'C++',
  'cpp': 'C++',
  'c#': 'C#',
  'csharp': 'C#',
  'c': 'C',
  'ruby': 'Ruby',
  'php': 'PHP',
  'swift': 'Swift',
  'kotlin': 'Kotlin',
  'scala': 'Scala',
  'elixir': 'Elixir',
  'dart': 'Dart',
  'r': 'R',
  'perl': 'Perl',
  'haskell': 'Haskell',
  'lua': 'Lua',
  'julia': 'Julia',
  'solidity': 'Solidity',
  'bash': 'Bash',
  'shell': 'Shell',
  'groovy': 'Groovy',
  'matlab': 'MATLAB',
  'sql': 'SQL',
} as const;